### ISSUE TITLE
'Broken Pipe' error when using start_http_server() with asyncio

### ISSUE THREAD

**Issue by markosaivaz** [prometheus/client_python#163]
I am exposing the metrics server, in a thread-heavy asyncio app.
All the work is done inside a ThreadPoolExecutor and inside each thread I increase a metric.
But after a while, I get a broken pipe error from exposition.py when prometheus server tries to read the metrics.
The metric is defined as a global variable.

Here is the stack trace:
<pre>
Exception happened during processing of request from ('10.0.4.18', 33086)
 Traceback (most recent call last):
   File "/usr/local/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
     self.process_request(request, client_address)
   File "/usr/local/lib/python3.5/socketserver.py", line 341, in process_request
     self.finish_request(request, client_address)
   File "/usr/local/lib/python3.5/socketserver.py", line 354, in finish_request
     self.RequestHandlerClass(request, client_address, self)
   File "/usr/local/lib/python3.5/socketserver.py", line 681, in __init__
     self.handle()
   File "/usr/local/lib/python3.5/http/server.py", line 422, in handle
     self.handle_one_request()
   File "/usr/local/lib/python3.5/http/server.py", line 410, in handle_one_request
     method()
   File "/usr/local/lib/python3.5/site-packages/prometheus_client/exposition.py", line 92, in do_GET
     self.wfile.write(output)
   File "/usr/local/lib/python3.5/socket.py", line 593, in write
     return self._sock.send(b)
 BrokenPipeError: [Errno 32] Broken pipe
</pre>

**Comment by brian-brazil** [comment]
That's the other end of the http connection closing the socket, likely due to a timeout.

**Comment by markosaivaz** [comment]
I undrestand that, but why would such a thing happen?
start_http_server is called, and the process is running as it is an http server.
There is also no way to debug this, as it is happening in the background.
Any chance it has to do with the threads?

**Comment by brian-brazil** [comment]
This is normal operations, there's nothing wrong here.

**Comment by markosaivaz** [comment]
So, both my server and the metrics server keep running, threads are fine to use, but there is this error, when the code never terminates the connection.
There is no way to configure/tweak the timeout of the server listening from what I understand.

Here is a snippet of how prometheus client is used in my code, in a last attempt:

**In main before starting the aiohttp server**
```python
if __name__ == "main":
    ...
    start_http_server(8002) 
    scrape_metrics = Counter("Somelabel", "Someinfo", [field1', 'field2', 'field3'])
    ...
```

**And in the function running in separate thread:**
```python
def function_running_in_thread(*args):
    ...
    scrape_metrics.labels(field1, field2, field3).inc(len(someIterable))
    ...
```

That's the only interaction with prometheus client there is in my code.
Last attempt for any ideas. I really appreciate it

**Comment by brian-brazil** [comment]
Once again, there is nothing wrong here on the client side. You might need to bump the scrape_timeout on Prometheus (though that'd be very surprising for direct instrumentation).

**Comment by yosefy** [comment]
i am having the same thing.
prometheus timeout is ok.
prometheus makes request, python starts its work end then first packet i see with tcpdump
goes from python client to prometheus and this error shows:

again prometheus is still waiting for reply (tried with browser and curl, same as prometheus)

same python2.7 and 3.5

thanks

Jan 21 16:22:36 ip-10-20-253-168 python3[2229]: ----------------------------------------
Jan 21 16:22:36 ip-10-20-253-168 python3[2229]: Exception happened during processing of request from ('127.0.0.1', 36904)
Jan 21 16:22:36 ip-10-20-253-168 python3[2229]: Traceback (most recent call last):
Jan 21 16:22:36 ip-10-20-253-168 python3[2229]:   File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
Jan 21 16:22:36 ip-10-20-253-168 python3[2229]:     self.finish_request(request, client_address)
Jan 21 16:22:36 ip-10-20-253-168 python3[2229]:   File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
Jan 21 16:22:36 ip-10-20-253-168 python3[2229]:     self.RequestHandlerClass(request, client_address, self)
Jan 21 16:22:36 ip-10-20-253-168 python3[2229]:   File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
Jan 21 16:22:36 ip-10-20-253-168 python3[2229]:     self.handle()
Jan 21 16:22:36 ip-10-20-253-168 python3[2229]:   File "/usr/lib/python3.5/http/server.py", line 422, in handle
Jan 21 16:22:36 ip-10-20-253-168 python3[2229]:     self.handle_one_request()
Jan 21 16:22:36 ip-10-20-253-168 python3[2229]:   File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
Jan 21 16:22:36 ip-10-20-253-168 python3[2229]:     method()
Jan 21 16:22:36 ip-10-20-253-168 python3[2229]:   File "/usr/local/lib/python3.5/dist-packages/prometheus_client/exposition.py", line 101, in do_GET
Jan 21 16:22:36 ip-10-20-253-168 python3[2229]:     self.wfile.write(output)
Jan 21 16:22:36 ip-10-20-253-168 python3[2229]:   File "/usr/lib/python3.5/socket.py", line 593, in write
Jan 21 16:22:36 ip-10-20-253-168 python3[2229]:     return self._sock.send(b)
Jan 21 16:22:36 ip-10-20-253-168 python3[2229]: BrokenPipeError: [Errno 32] Broken pipe

**Comment by ilaipx** [comment]
I also get this rather randomly, although I see the scraped metrics in Prometheus.

**Comment by loulloudesn** [comment]
Hi, same here...I randomly get Broken Pipe error on my custom exporters.

- Prometheus client v.0.2.0
- Exporters are running on Python 2.7
- Prometheus scrape interval is set to 10 mins

**Comment by fruch** [comment]
I'm having the exact same issue, I have lots of threads reporting metrics every second or so, and the scrape time is 30sec

**Comment by frankcash** [comment]
I am also facing a similar issue with my threads.

**Comment by alex25555** [comment]
I am also facing the same problem. It runs ok for the first 2 hours without any errors but later fails with the socket and broken pipe, during which no metrics are coming into Prometheus. I played with the timeouts and intervals but no luck. I am running the K8 Prometheus stack. Any help would be appreciated. 

Exception happened during processing of request from xxxxxxxxxxx
error: [Errno 32] Broken pipe
19:47:14 DEBUG Collection times 1890 (ms): {'clouddriver': 1890}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/local/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/local/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/local/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
19:47:19 DEBUG Collection times 1909 (ms): {'clouddriver': 1909}

**Comment by sidps** [comment]
@brian-brazil is there some way these exceptions can be handled? At the least, it's polluting logs, and we'd like to stop it from doing so.

**Comment by aihuoye** [comment]
@brian-brazil I'm having the same problem. And when it is happend some time, Prometheus server fetch data failed, and i can't see the data on the Grafna.

Exception happened during processing of request from ('116.231.26.205', 52764)
Traceback (most recent call last):
  File "/data/anaconda3/envs/py37/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/data/anaconda3/envs/py37/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data/anaconda3/envs/py37/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/data/anaconda3/envs/py37/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/data/anaconda3/envs/py37/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/data/anaconda3/envs/py37/lib/python3.7/site-packages/prometheus_client/exposition.py", line 159, in do_GET
    self.wfile.write(output)
  File "/data/anaconda3/envs/py37/lib/python3.7/socketserver.py", line 799, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('116.231.26.205', 52786)
Traceback (most recent call last):
  File "/data/anaconda3/envs/py37/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/data/anaconda3/envs/py37/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data/anaconda3/envs/py37/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/data/anaconda3/envs/py37/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/data/anaconda3/envs/py37/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/data/anaconda3/envs/py37/lib/python3.7/site-packages/prometheus_client/exposition.py", line 159, in do_GET
    self.wfile.write(output)
  File "/data/anaconda3/envs/py37/lib/python3.7/socketserver.py", line 799, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by brian-brazil** [comment]
Please don't ask usage questions on closed issues. 
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
