### ISSUE TITLE
Got error when running 

### ISSUE THREAD

**Issue by thanh3d** [prometheus/client_python#171]
```
Exception happened during processing of request from ('127.0.0.1', 65353)
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/private/var/root/client_python/prometheus_client/exposition.py", line 86, in do_GET
    output = generate_latest(registry)
  File "/private/var/root/client_python/prometheus_client/exposition.py", line 72, in generate_latest
    for k, v in sorted(labels.items())]))
AttributeError: 'set' object has no attribute 'items'
----------------------------------------
```

**Comment by thanh3d** [comment]
I define 

```
metric = Metric('prometheus_notifications',
        'Requests time taken in seconds', 'summary')

    metric.add_sample('Payment_status',
        value=text['ip'], labels={0})
    yield metric

```

**Comment by brian-brazil** [comment]
Usage questions should be asked at https://groups.google.com/forum/#!forum/prometheus-users where everyone can benefit from the answers.
