### ISSUE TITLE
ImportError: cannot import name 'start_http_server' from 'prometheus_client' (Python 3.7.0a2)

### ISSUE THREAD

**Issue by drno-reg** [prometheus/client_python#230]
Hello,

OS Windows 8.1
Python 3.7.0a2

tryed to excute code

```
#!/usr/local/bin/python
# coding: utf-8

from prometheus_client import start_http_server, Summary
import random
import time

# Create a metric to track time spent and requests made.
REQUEST_TIME = Summary('request_processing_seconds', 'Time spent processing request')

# Decorate function with metric.
@REQUEST_TIME.time()
def process_request(t):
    """A dummy function that takes some time."""
    time.sleep(t)

if __name__ == '__main__':
    # Start up the server to expose the metrics.
    start_http_server(8000)
    # Generate some requests.
    while True:
        process_request(random.random())
```

returned error

```
Traceback (most recent call last):
  File "C:/Server/Repositories/Projects/um_open/templates/Test/prometheus_client.py", line 4, in <module>
    from prometheus_client import start_http_server, Summary
  File "C:\Server\Repositories\Projects\um_open\templates\Test\prometheus_client.py", line 4, in <module>
    from prometheus_client import start_http_server, Summary
ImportError: cannot import name 'start_http_server' from 'prometheus_client' (C:\Server\Repositories\Projects\um_open\templates\Test\prometheus_client.py)
```

How solve this problem?

**Comment by brian-brazil** [comment]
This sounds like a problem with your environment. How did you install the client?

**Comment by drno-reg** [comment]
pip install prometheus_client

**Comment by brian-brazil** [comment]
What version is that, and is the path it installed to in your sys.path?

**Comment by drno-reg** [comment]
Collecting prometheus_client
  Using cached prometheus_client-0.1.0.tar.gz
Installing collected packages: prometheus-client
  Running setup.py install for prometheus-client ... done
Successfully installed prometheus-client-0.1.0

**Comment by drno-reg** [comment]
'C:\\Python37\\python37.zip',
 'C:\\Python37\\DLLs',
 'C:\\Python37\\lib',
 'C:\\Python37',
 'C:\\Python37\\lib\\site-packages'

**Comment by drno-reg** [comment]
returned after executed python script

import sys
from pprint import pprint as p
p(sys.path)

**Comment by drno-reg** [comment]
I understood where was mistake, name my python app same with name file in module prometheus_client
