### ISSUE TITLE
Cannot run example from readme

### ISSUE THREAD

**Issue by psafont** [prometheus/client_python#255]
Using a python 3.6 virtual environment:

```
$ pip install prometheus_client
Collecting prometheus_client
Installing collected packages: prometheus-client
Successfully installed prometheus-client-0.1.1
$ python
Python 3.6.4 (default, Jan  5 2018, 02:35:40)
[GCC 7.2.1 20171224] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from prometheus_client import start_http_server, Summary
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: bad magic number in 'prometheus_client': b'\x03\xf3\r\n'
>>>
$ pip freeze
prometheus-client==0.1.1
```
Very strange since there seems to be a window's newline (I'm using Linux)

Using a python 2.7 virtual environment:

```
$ pip install prometheus_client
Collecting prometheus_client
Installing collected packages: prometheus-client
Successfully installed prometheus-client-0.1.1
$ python
Python 2.7.14 (default, Jan  5 2018, 10:41:29)
[GCC 7.2.1 20171224] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from prometheus_client import start_http_server, Summary
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/psafont/dev/misc/sqlalchemy/prometheus_client.py", line 1, in <module>
ImportError: cannot import name start_http_server
>>>
$ pip freeze
prometheus-client==0.1.1
```

Which is very weird, since I can see the start_http_server in prometheus_client.__init__

I've no idea what's going on, any hints on what might be happening?

**Comment by brian-brazil** [comment]
It sounds like you have some bad/old pyc files. Try deleting them.

**Comment by psafont** [comment]
You were right, thanks!
