### ISSUE TITLE
Passing a dictionary as label: values 

### ISSUE THREAD

**Issue by 4n4nd** [prometheus/client_python#295]
I am trying the snippet below in python3:
```
from prometheus_client import Gauge

# This is a sample label:value dictionary
test_label_dict = {"abc":"123", "def":"456"}

VALUE = Gauge('metric_name', 'metric description', test_label_dict.keys())  # VALUE is a gauge metric

VALUE.labels(test_label_dict).set(4.2) #Give values to the labels and set the value for the metric
```

But the last line gives me the following error:
```
Traceback (most recent call last):
  File "prom_client.py", line 8, in <module>
    VALUE.labels(test_label_dict).set(4.2) #Give values to the labels and set the value for the metric
  File "/home/4n4nd/miniconda3/lib/python3.6/site-packages/prometheus_client/core.py", line 561, in labels
    raise ValueError('Incorrect label count')
ValueError: Incorrect label count

```

In the source code, I saw that kwargs can be passed to the function (Here: https://github.com/prometheus/client_python/blob/master/prometheus_client/core.py#L529)

**Comment by 4n4nd** [comment]
That works,

Thanks
