### ISSUE TITLE
ValueError: invalid literal for float()

### ISSUE THREAD

**Issue by christopherhans** [prometheus/client_python#337]
Hi,
I'm currently trying to export a version number. But the exporter fails, if the version is a multi dotted string.

```
import json
import sys
import time

import requests

from prometheus_client import REGISTRY, Metric, start_http_server

class VersionCollector(object):
 
  def __init__(self, host, port, username, password):
    self._host = host
    self._port = port
    self._username = username
    self._password = password

 def collect(self):
    test = dict()
    test.update(version=7.1.1)

    metric = Metric('my_version',
        'Version', 'info')
    metric.add_sample('my_version',
        value=test['version'], labels={})
    yield metric
    
if __name__ == '__main__':
  start_http_server(int(sys.argv[1]))
  REGISTRY.register(VersionCollector(sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5]))
  while True: time.sleep(1)
````
The test dictionary is only for testing purpose (surprise..). Originally I take my sample data from a different service, that's why there is all this host and port stuff. I didn't wanted to delete all this for this example.

Running the code with `version=7.1` works fine. But if I run this example with `version=7.1.1`the execution fails with the error massage:
```
Traceback (most recent call last):
  File "version_exporter.py", line 58, in <module>
    REGISTRY.register(VersionCollector(sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5]))
  File "/usr/local/lib/python2.7/site-packages/prometheus_client/core.py", line 96, in register
    names = self._get_names(collector)
  File "/usr/local/lib/python2.7/site-packages/prometheus_client/core.py", line 136, in _get_names
    for metric in desc_func():
  File "version_exporter.py", line 50, in collect
    value=float(test['version']), labels={})
ValueError: invalid literal for float(): 7.1.1
```
Am I using the prometheus API wrong, or is prometheus only capable of handling "float-like" outputs? How can I make my exporter working?

Many thanks in advance :)

**Comment by brian-brazil** [comment]
All values are floats. Try using an Info metric.
