### ISSUE TITLE
prometheus client cannot merge stats data from across VMs or Hosts

### ISSUE THREAD

**Issue by pingc-sh** [prometheus/client_python#352]
Hi there
We deploy our API in K8S cluster, our API Pods located in different VMs of the K8S cluster. We encountered an issue that when Prometheus client doing stats data merge, it fails as mmap issue, mmap works fine if API instances runing in same host, in our case mmap won't work, is there any way that Prometheus client can do stats data merge across hosts? or do you have plan to enable it? thanks.

`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/capacity-tool/api/__init__.py", line 114, in metrics
    data = generate_latest(registry)
  File "/usr/local/lib/python3.6/site-packages/prometheus_client/exposition.py", line 87, in generate_latest
    for metric in registry.collect():
  File "/usr/local/lib/python3.6/site-packages/prometheus_client/core.py", line 147, in collect
    for metric in collector.collect():
  File "/usr/local/lib/python3.6/site-packages/prometheus_client/multiprocess.py", line 27, in collect
    return self.merge(files, accumulate=True)
  File "/usr/local/lib/python3.6/site-packages/prometheus_client/multiprocess.py", line 40, in merge
    d = core._MmapedDict(f, read_mode=True)
  File "/usr/local/lib/python3.6/site-packages/prometheus_client/core.py", line 538, in __init__
    _pack_integer(self._m, 0, self._used)
  File "/usr/local/lib/python3.6/site-packages/prometheus_client/core.py", line 513, in _pack_integer
    data[pos:pos + 4] = _pack_integer_func(value)
TypeError: mmap can't modify a readonly memory map.`

**Comment by brian-brazil** [comment]
Multiprocess mode is only meant to work on one machine.

**Comment by pingc-sh** [comment]
Hi Brian

In this case(client instances runs in different machines), is there anyway to collect the complete data from client side? Currently when we read stats data from API endpoint, we only get data from one instance

Can Prometheus server discover all client instances and fetch the complete data? or does Prometheus client instance need to register themselves to Prometheus server for the service discovery?
Thanks.

**Comment by brian-brazil** [comment]
You're looking for service discovery.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
