### ISSUE TITLE
Exception while processing request in custom exporter

### ISSUE THREAD

**Issue by dtolj** [prometheus/client_python#494]
I have increased the number of points over 1000 and started to see this error. 

`Exception happened during processing of request from ('10.102.113.108', 50670)
Traceback (most recent call last):
  File "/usr/lib64/python3.6/socketserver.py", line 639, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.6/socketserver.py", line 696, in __init__
    self.handle()
  File "/usr/lib64/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "/root/.pex/install/prometheus_client-0.7.1-py3-none-any.whl.06415bcb7c0b3633c5ccf0878d4a58913f999a41/prometheus_client-0.7.1-py3-none-any.whl/prometheus_client/exposition.py", line 159, in do_GET
    self.wfile.write(output)
  File "/usr/lib64/python3.6/socketserver.py", line 775, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe`

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
