### ISSUE TITLE
Exception occurred during processing of request from ('10.12.220.146', 52792)

### ISSUE THREAD

**Issue by eminaktas** [prometheus/client_python#590]
I am not sure if this is happening because of prometheus pyhton source code. I have been looking this error but could not figure out what is going on. Can anyone please tell me what it is happening here?

I deployed a custom exporter as a container in a kubernetes cluster and expose the metrics on a http server. 

Here is my code: https://github.com/eminaktas/get-of-metrics/blob/master/get-of-metrics.py

`Exception occurred during processing of request from ('10.12.220.146', 52792)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.9/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.9/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.9/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/local/lib/python3.9/site-packages/prometheus_client/exposition.py", line 152, in do_GET
    output = encoder(registry)
  File "/usr/local/lib/python3.9/site-packages/prometheus_client/openmetrics/exposition.py", line 14, in generate_latest
    for metric in registry.collect():
  File "/usr/local/lib/python3.9/site-packages/prometheus_client/registry.py", line 75, in collect
    for metric in collector.collect():
  File "/get-of-metrics/./get-of-metrics-v2.py", line 70, in collect
    matches = finditer(regex, data)
  File "/usr/local/lib/python3.9/re.py", line 248, in finditer
    return _compile(pattern, flags).finditer(string)
TypeError: expected string or bytes-like object`

Thank you

**Comment by brian-brazil** [comment]
That is an error entirely in your code, nothing to do with this library.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
