### ISSUE TITLE
Sending Info object to push gateway

### ISSUE THREAD

**Issue by akshaysgithub** [prometheus/client_python#598]
Hello, 

I want to send individual log file lines to push-gateway. The best case I thought of this was to use Info object. The below mentioned code is working for Summary or Gauge, but not for Info. I am getting an iteration warning. What am I doing wrong? I am new to python and prometheus/push-gateway. 

Error log : 

```
Traceback (most recent call last):
  File "complete.py", line 21, in <module>
    _send_data_to_gateway(line)
  File "complete.py", line 6, in _send_data_to_gateway
    i = Info('supplier_log_file', 'supplier_infor', reg)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/prometheus_client/metrics.py", line 101, in __init__
    self._labelnames = _validate_labelnames(self, labelnames)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/prometheus_client/metrics.py", line 40, in _validate_labelnames
    labelnames = tuple(labelnames)
TypeError: 'CollectorRegistry' object is not iterable
```

Code : 

```

from prometheus_client import Info, CollectorRegistry, push_to_gateway
import time

def _send_data_to_gateway(line):
    reg = CollectorRegistry()
    i = Info('supplier_log_file', 'supplier_infor', reg)
    i.info({line})
    push_to_gateway('localhost:9091', job='supplier_log_file', registry=reg)


f = open('/var/log/nginx/access.log', 'r')
while True:
    line = ''
    while len(line) == 0 or line[-1] != '\n':
        tail = f.readline()
        if tail == '':
            time.sleep(0.1)          # avoid busy waiting
            continue
        line += tail
        print(line)
        _send_data_to_gateway(line)

```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
