### ISSUE TITLE
Broken pipe in collector.

### ISSUE THREAD

**Issue by reformstudios** [prometheus/client_python#606]
I've got a pretty simple collector that's querying an api in the collect() method. The problem is that I'm getting a broken pipe often, even after increasing the scrape_interval substantially it's still happening. 

Here's the stack trace : 

```
Exception happened during processing of request from ('172.20.0.2', 59810)

Traceback (most recent call last):

File "/usr/local/lib/python3.7/socketserver.py", line 650, in process_request_thread

self.finish_request(request, client_address)

File "/usr/local/lib/python3.7/socketserver.py", line 360, in finish_request

self.RequestHandlerClass(request, client_address, self)

File "/usr/local/lib/python3.7/socketserver.py", line 720, in __init__

self.handle()

File "/usr/local/lib/python3.7/http/server.py", line 426, in handle

self.handle_one_request()

File "/usr/local/lib/python3.7/http/server.py", line 414, in handle_one_request

method()

File "/usr/local/lib/python3.7/site-packages/prometheus_client/exposition.py", line 159, in do_GET

self.wfile.write(output)

File "/usr/local/lib/python3.7/socketserver.py", line 799, in write

self._sock.sendall(b)

BrokenPipeError: [Errno 32] Broken pipe


```

and here's my collector : 

```
def collect(self):
        logging.info("collect : {}".format(self))
        g = GaugeMetricFamily("sg_one_time_query", 'Help text', labels=['site', 'field'])

        data = self.get_shotgun_API_response()
        logging.info("data : {}".format(data))
        if data:
            g.add_metric([_SG_SCRIPT_SITE, 'sg_one_time_query'], data['sg_one_time_query'])
            g.add_metric([_SG_SCRIPT_SITE, 'sg_one_time_update'], data['sg_one_time_update'])
            g.add_metric([_SG_SCRIPT_SITE, 'sg_open_ended_query'], data['sg_open_ended_query'])
            yield g
```

Any ideas? I'm running this collector in a docker container. I'm getting values most of the time, but the error above is polluting the data quite often with zero values.

(I'm new to prometheus so most likely doing something wrong!)

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by reformstudios** [comment]
Sorry Brian, and thanks for the pointer. I have posted there also.
p.
