### ISSUE TITLE
Error "Status must be a string" happened with Python2.7

### ISSUE THREAD

**Issue by Travis-Sun** [prometheus/client_python#662]
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "build/bdist.linux-x86_64/egg/prometheus_client/exposition.py", line 125, in prometheus_app
    start_response(status, [header])
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 173, in start_response
    assert type(status) is StringType,"Status must be a string"
AssertionError: Status must be a string

**Comment by csmarchbanks** [comment]
Thank you for the report, do you have a small example that reproduces this issue?

**Comment by Geethree** [comment]
Yeah I just hit this in py2.7 as well. This appears to be a py2/py3 string issue.
In py2 [status](https://github.com/prometheus/client_python/blob/master/prometheus_client/exposition.py#L125) should be encoded and in py3 it should be a string.

I worked around this for another thing by just casting `status` to `str(status)`

Simple reproduced issue here: https://github.com/Geethree/prometheus-py27-string-bug

I'll open a pull request
