### ISSUE TITLE
AttributeError: 'Histogram' object has no attribute '_sum'

### ISSUE THREAD

**Issue by cunningr** [prometheus/client_python#681]
Maybe I am doing something wrong when trying to use Histogram (the docs are not entirely clear) but I am getting:

```
Traceback (most recent call last):
  File "/Users/cunningr/umbrella/git_other/metrics/custom_metrics.py", line 72, in <module>
    asyncio.run(main())
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/cunningr/umbrella/git_other/metrics/custom_metrics.py", line 66, in main
    await asyncio.gather(update_data('vtktools_data.txt'))
  File "/Users/cunningr/umbrella/git_other/metrics/custom_metrics.py", line 27, in update_data
    h.observe(randnum)
  File "/Users/cunningr/virtualenv/general/lib/python3.9/site-packages/prometheus_client/metrics.py", line 554, in observe
    self._sum.inc(amount)
AttributeError: 'Histogram' object has no attribute '_sum'
```

when trying to use histogram like so:

```
            bucket_values = (1, 256, 512, 1024, 2048, 4096, 8192, 16384, float("inf"))
            h = Histogram('my_histo', 'Help text', labelnames=['DC1'], buckets=bucket_values)
            randnum = random.randrange(16384)
            h.observe(randnum)
```

in the code I also couldn't find where the `_sum` attribute is defined.

**Comment by csmarchbanks** [comment]
Hello, you are not defining your label values before observing on your histogram. You will need something like:
```
h.labels('DC1_value').observe(randnum)
```
in your example.

In the next release the error message will be improved to say `ValueError: histogram metric is missing label values` instead of the rather unhelpful error currently provided (that work was done in https://github.com/prometheus/client_python/pull/666).

I am closing this issue as the error messaging has already been improved.
