### ISSUE TITLE
`start_http_server` fails when given an IPv6 address to bind

### ISSUE THREAD

**Issue by prophile** [prometheus/client_python#69]
It would be good not to force an IPv4 fallback.

**Comment by brian-brazil** [comment]
What was the exact code you used?

**Comment by prophile** [comment]
```
% python                                                                                                                                    [master] 
Python 3.5.0 (default, Sep 14 2015, 02:37:27) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import prometheus_client
>>> prometheus_client.start_http_server(port=9097, addr='::')
>>> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 923, in _bootstrap_inner
    self.run()
  File "/Users/alynn/Thread/hamon/venv/lib/python3.5/site-packages/prometheus_client/exposition.py", line 64, in run
    httpd = HTTPServer((addr, port), MetricsHandler)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 443, in __init__
    self.server_bind()
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 457, in server_bind
    self.socket.bind(self.server_address)
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

**Comment by brian-brazil** [comment]
That looks more like an issue down in cPython, we're passing the `addr` straight down.

**Comment by rud** [comment]
Vote to close.
