### ISSUE TITLE
Internal Sever Error when trying to see metrics via locust_exporter

### ISSUE THREAD

**Issue by ruchikakhemka** [prometheus/client_python#790]
Hi , 
I am using locust_exporter from https://github.com/mbolek/locust_exporter . When  running the exporter I am getting Internal server error on the browser and following error is displayed on the terminal :

Traceback (most recent call last):
File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/wsgiref/handlers.py", line 137, in run
self.result = application(self.environ, self.start_response)
File "/Users/locust_exporter/.venv/lib/python3.9/site-packages/prometheus_client/exposition.py", line 118, in prometheus_app
status, header, output = _bake_output(registry, accept_header, params)
File "/Users/locust_exporter/.venv/lib/python3.9/site-packages/prometheus_client/exposition.py", line 100, in bake_output
output = encoder(registry)
File "/Users/locust_exporter/.venv/lib/python3.9/site-packages/prometheus_client/exposition.py", line 202, in generate_latest
output.append(sample_line(s))
File "/Users/locust_exporter/.venv/lib/python3.9/site-packages/prometheus_client/exposition.py", line 159, in sample_line
['{}="{}"'.format(
File "/Users/locust_exporter/.venv/lib/python3.9/site-packages/prometheus_client/exposition.py", line 160, in
k, v.replace('\', r'\').replace('\n', r'\n').replace('"', r'"'))
AttributeError: ("'NoneType' object has no attribute 'replace'", Metric(locust_requests_avg_content_length, Locust requests avg_content_length, gauge, , [Sample(name='locust_requests_avg_content_length', labels={'path': '/api/test, 'method': 'POST'}, value=165.0, timestamp=None, exemplar=None), Sample(name='locust_requests_avg_content_length', labels={'path': 'Aggregated', 'method': None}, value=165.0, timestamp=None, exemplar=None)]))

**Comment by ruchikakhemka** [comment]
Anyone looking into this?
