### ISSUE TITLE
Duplicated timeseries in CollectorRegistry

### ISSUE THREAD

**Issue by shaung** [prometheus/client_python#818]
Code:

    from prometheus_client import Gauge, Counter
    a = Gauge('request', 'test')
    b = Counter('request_total', 'test')

Output:

    Traceback (most recent call last):
      File "main.py", line 4, in <module>
        c = Counter('request_total', 'test')
      File "lib/python3.10/site-packages/prometheus_client-0.12.0-py3.10.egg/prometheus_client/metrics.py", line 136, in __init__
        registry.register(self)
      File "lib/python3.10/site-packages/prometheus_client-0.12.0-py3.10.egg/prometheus_client/registry.py", line 30, in register
        raise ValueError(
     ValueError: Duplicated timeseries in CollectorRegistry: {'request'}

I understand that `_total` suffix would be removed and automatically added afterwards, but this behavior makes some metrics broken --

**Comment by paketb0te** [comment]
... rename one of the metrics? :grin:
