### ISSUE TITLE
"Duplicated timeseries in CollectorRegistry" before adding label values

### ISSUE THREAD

**Issue by octopoulpe** [prometheus/client_python#821]
Hi.

It seems we cannot create multiple gauges with the same name and different label values.
This is a simple example where changing auto_describe to True on the registry doesn't change anything to the error.

```
from prometheus_client.openmetrics.exposition import generate_latest
from prometheus_client import Gauge, CollectorRegistry

registry = CollectorRegistry(auto_describe=True)

g = Gauge(
    "foo",
    "bar",
    labelnames=["a", "b"],
    registry=registry,
    unit="degrees",
)
g = g.labels(a="aaa", b="bbb")
g.set(0.5)

h = Gauge(
    "foo",
    "bar",
    labelnames=["a", "b"],
    registry=registry,
    unit="degrees",
)
h = h.labels(a="xxx", b="yyy")
h.set(0.5)


print(generate_latest(registry).decode())
```

Stack Trace :
```
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    h = Gauge(
  File "/usr/lib/python3.10/site-packages/prometheus_client/metrics.py", line 365, in __init__
    super().__init__(
  File "/usr/lib/python3.10/site-packages/prometheus_client/metrics.py", line 143, in __init__
    registry.register(self)
  File "/usr/lib/python3.10/site-packages/prometheus_client/registry.py", line 43, in register
    raise ValueError(
ValueError: Duplicated timeseries in CollectorRegistry: {'foo_degrees'}
```

We think the result should be something like :
```
foo_degrees{a="aaa",b="bbb"} 0.5
foo_degrees{a="xxx",b="yyy"} 0.5
```

It fails before we can set the label values on the second gauge.

We think the cause is `MetricWrapperBase` defining an incomplete `describe` method but not sure we really understood what we should do.

**Comment by csmarchbanks** [comment]
Hello, I am curious what your use case is for creating two metrics with the same labels rather than just using your first gauge for everything? In your case, call `g = g.labels(a="xxx", b="yyy")` instead of `h = h.labels(a="xxx", b="yyy")` and do not create `h` at all.

This behavior comes down to the [OpenMetrics spec](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#name) where the names of all metric families must be unique and this client creates a new metric family for each Gauge/Counter/etc... created.

**Comment by octopoulpe** [comment]
Hi.
Yes that was it. We didn't understand only one Gauge should be created for each metric type.

It works perfectly now. Thanks a lot.
