### ISSUE TITLE
Error while calling the remove method

### ISSUE THREAD

**Issue by cmarasescu** [prometheus/client_python#835]
Hello,

I'm getting the below error while trying to call the `remove` method for a metric.
```
WARNING stdout F WARNING __main__.py        __main__        : PODMAN check - We need to remove this metric, as its a duplicate of the current metric due to a change of labels <podman_check{container="coredns-tu",id="f92a9532e505",image="192.168.31.10:5000/test/coredns:0.1",state="running",username="root"}>
ERROR stdout F ERROR __main__.py        __main__        : PODMAN check - exception while trying to remove old metrics, exception => ('coredns-tu', 'f92a9532e505', '192.168.31.10:5000/test/coredns:0.1', 'running', 'root')
stdout F Traceback (most recent call last):
stdout F   File "/usr/local/lib/python3.10/site-packages/app_check/__main__.py", line 706, in remove_metrics_for_removed_containers
stdout F     podman_metric.remove(old_container_name, old_container_id, old_container_image, old_container_state, old_username)
stdout F   File "/usr/local/lib/python3.10/site-packages/prometheus_client/metrics.py", line 209, in remove
stdout F     del self._metrics[labelvalues]
stdout F KeyError: ('coredns-tu', 'f92a9532e505', '192.168.31.10:5000/test/coredns:0.1', 'running', 'root')
```
Am I calling the remove method using the wrong parameters or is there a bug here?

The code for setting up the metrics is omething like this:
```
podman_check_metric = Gauge('podman_check', 'Checks if podman containers are up and running', ['container', 'id', 'username', 'image', 'state']) 
.................
podman_check_metric.labels(container_name, container_id, username, container_image, container_state).set(container_status)
```

I've added some dynamic labels, because besides the podman container status (1=Running, 0=NOK), I also need to build some dashboards showing in example which image version is used for every container.

However, it seems that once my podman containers are being updated (the id, status or image changes), I end-up with duplicate metrics (my current container has the id "5df23ddbd37b", but I can still see a metric for the previous instance of my container - f92a9532e505):
```
curl http://localhost:8080/metrics | grep ^podman_check
podman_check{container="coredns-tu",id="f92a9532e505",image="192.168.31.10:5000/test/coredns:0.1",state="running",username="root"} 1.0
podman_check{container="coredns-tu",id="5df23ddbd37b",image="192.168.31.10:5000/test/coredns:0.1",state="running",username="root"} 1.0
```

In order to remove the duplicates, I've tried to check the duplicates and remove the no longer relevant metric, using the following code:
```
podman_metric.remove(container_name, old_container_id, container_image, container_state, username)
```

**Comment by cmarasescu** [comment]
I've solved this myself.

It seems that the remove method works just fine using the same parameters as in labels method, it's just that I've put the parameters in a wrong order

```
podman_check_metric = Gauge('podman_check', 'Checks if podman containers are up and running', ['container', 'id', 'username', 'image', 'state']) 

#WRONG order
podman_metric.remove(container_name, old_container_id, container_image, container_state, username)

#GOOD order
podman_metric.remove(container_name, old_container_id, username, container_image, container_state)
```
