### ISSUE TITLE
generate_latest causes a 500 internal server error

### ISSUE THREAD

**Issue by rvalkenaers** [prometheus/client_python#90]
I'm using https://github.com/ekesken/prom_marathon_exporter to get metrics from marathon.

It uses the generate_latest function from exposition.py which seems to crash on following metric: "jvm.threads.deadlocks":{"value":[]} which is in the gauges array on the marathon master. It is expecting a float in stead of an empty array.

I'm currently using marathon Version 1.1.2.

I'm not sure whether this is an issue with this module or with the prom_marathon_exporter.

Stacktrace:
ERROR:http:Exception on /metrics [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/prom_marathon_exporter/http.py", line 25, in metrics
    prom_metrics = generate_latest(REGISTRY)
  File "/usr/local/lib/python2.7/dist-packages/prometheus_client/exposition.py", line 67, in generate_latest
    output.append('{0}{1} {2}\n'.format(name, labelstr, core._floatToGoString(value)))
  File "/usr/local/lib/python2.7/dist-packages/prometheus_client/core.py", line 558, in _floatToGoString
    elif math.isnan(d):
TypeError: a float is required

**Comment by brian-brazil** [comment]
What are you expecting here? The exception is correct.

**Comment by rvalkenaers** [comment]
I updated my initial comment: 

I'm not sure whether this is an issue with this module or with the prom_marathon_exporter.

**Comment by rvalkenaers** [comment]
I'll close the issue
