### ISSUE TITLE
Metrics all to zero ... noob

### ISSUE THREAD

**Issue by eMerzh** [prometheus/client_python#98]
Hi, 
thanks for your work on the lib! 
disclaimer: i'm a noob in prometheus and in using this lib... so i might miss something obvious 

i'm trying to use it in my flask app
so i did : 

```
c = Counter('my_failures_total', 'Description of counter')

@app.route('/brol')
def brol():
    c.inc()     # Increment by 1
    c.inc(1.6)  # Increment by given value
    return 'hello world'


if __name__ == '__main__':
    start_http_server(9012)
    app.run()
```

i go with my browser on localhost:5000/brol  multiple times... 
then go to localhost:9012 and the response i got is  : 

```
# HELP my_failures_total Description of counter
# TYPE my_failures_total counter
my_failures_total 0.0
```

even if i refresh /brol or :9012 the my_failures_total is always 0.

btw i often got in my console

```

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/bmaron/Code/profiler-gui/venv/lib/python2.7/site-packages/prometheus_client/exposition.py", line 86, in run
    httpd = HTTPServer((addr, port), MetricsHandler)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 48] Address already in use
```

i suppose it's related, but tried to relaunch, change port, ... it seems to be caused by the way i instantiate the start_http_server

**Comment by brian-brazil** [comment]
Are you running in a multi-process mode such as unicorn?

**Comment by eMerzh** [comment]
nope just launching 
```
 python run.py
```
in DEBUG mode...

**Comment by brian-brazil** [comment]
Are you sure you're talking to the process you think you are? Check with `sudo netstat -nlpt`.

**Comment by eMerzh** [comment]
mmmh interessting... seems to work without debug...
might be the reload mode of flask?

how am i supposed to deal with that ?

**Comment by brian-brazil** [comment]
I don't know enough about the internals of flask to say.

**Comment by rafi** [comment]
In development mode, when starting a Werkzeug single process it seems that `prometheus_client.start_http_server` immediately triggers Flask's reload and "reboots" the process and then crashes because address/port is already in use. 

It's possible to disable reload with adding the `use_reloader=False` parameter when instantiating app object, but I wish I knew what's the root cause..
